[versions]
agp = "8.5.2"
core-testing = "2.2.0"
kotlin = "2.0.20"
kotlin-test-junit = "2.0.20"
kotlinx-coroutines-test = "1.7.3"
ksp = "2.0.20-1.0.24"
compose-bom = "2024.10.00"
activity-compose = "1.9.3"
material3 = "1.3.0"
mockk = "1.13.12"
navigation-compose = "2.8.2"
hilt = "2.52"
hilt-nav-compose = "1.2.0"
coroutines = "1.8.1"
lifecycle = "2.8.6"
material = "1.12.0"
serialization = "1.7.3"
okhttp = "4.12.0"
retrofit = "2.11.0"
coil = "2.7.0"
turbine = "1.1.0"
junit4 = "4.13.2"
ui-test = "1.9.4"
ui-test-junit4 = "1.9.4"
ui-test-junit4-android = "1.9.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization= { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose",       version.ref = "kotlin" }
hilt                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
androidx-compose-bom                = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-activity-compose           = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-ui                         = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "ui-test" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-junit4" }
androidx-ui-tooling                 = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview         = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3                  = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material-icons-extended    = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation-compose         = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-lifecycle-runtime-ktx      = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel        = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose= { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

hilt-android            = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler           = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt",     name = "hilt-navigation-compose", version.ref = "hilt-nav-compose" }

kotlin-bom                  = { group = "org.jetbrains.kotlin",   name = "kotlin-bom",                 version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-test-junit" }
kotlinx-coroutines-android  = { group = "org.jetbrains.kotlinx",  name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test-v173 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-serialization-json  = { group = "org.jetbrains.kotlinx",  name = "kotlinx-serialization-json", version.ref = "serialization" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okhttp-core     = { group = "com.squareup.okhttp3",  name = "okhttp",               version.ref = "okhttp" }
okhttp-logging  = { group = "com.squareup.okhttp3",  name = "logging-interceptor",  version.ref = "okhttp" }
retrofit-core   = { group = "com.squareup.retrofit2",name = "retrofit",             version.ref = "retrofit" }
retrofit-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
material     = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "ui-test-junit4-android" }